name: oauth_dio
description: A customizable oauth client with token storage and interceptors for dio
version: 0.2.4-beta1
homepage: https://github.com/salomaosnff/oauth_dio

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  dio:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
